name: Build Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  VIRTUALBOX_VERSION: "7.1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup HashiCorp Packer
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232
        uses: hashicorp/setup-packer@v3.1.0
        with:
          # The Packer version to install and add to PATH.
          version: latest
      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1 
        with:
          version: "9.3.0"
      - name: "Print Ansible version"
        run: ansible-playbook --version

      - name: "Virtualbox - deps"
        run: "sudo apt install software-properties-common"

      - name: "Virtualbox - Install Oracle GPG Key"
        run: "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -"

      - name: "Virtualbox - Install Repo"
        run: "echo \"deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib\" | sudo tee /etc/apt/sources.list.d/virtualbox.list"

      - name: "Virtualbox - update"
        run: "sudo apt update"
      - name: "Virtualbox - Install Virtualbox"
        run: sudo apt install virtualbox-${{ env.VIRTUALBOX_VERSION }}


      - name: Run packer init
        working-directory: "./packer"
        run: "packer init ."
      - name: Run packer validate
        working-directory: "./packer"
        run: "packer validate ."
      
          
