name: Build Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  VIRTUALBOX_MAJOR_VERSION: "7.1"
  VIRTUALBOX_VERSION: "7.1.14"
  VIRTUALBOX_EXT_PACK_LICID: "33d7284dc4a0ece381196fda3cfe2ed0e1e8e7ed7f27b9a9ebc4ee22e24bd23c"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup HashiCorp Packer
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232
        uses: hashicorp/setup-packer@v3.1.0
        with:
          # The Packer version to install and add to PATH.
          version: latest
      - name: "Install Ansible"
        uses: alex-oleshkevich/setup-ansible@v1.0.1 
        with:
          version: "9.3.0"
      - name: "Print Ansible version"
        run: ansible-playbook --version

      - name: "Virtualbox - deps"
        run: "sudo apt install software-properties-common"

      - name: "Virtualbox - Install Oracle GPG Key"
        run: "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -"

      - name: "Virtualbox - Install Repo"
        run: "echo \"deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib\" | sudo tee /etc/apt/sources.list.d/virtualbox.list"

      - name: "Virtualbox - update"
        run: "sudo apt update"

      - name: "Virtualbox - Install Virtualbox"
        run: sudo apt install virtualbox-${{ env.VIRTUALBOX_MAJOR_VERSION }}

      - name: "Virtualbox - Download Extension pack"
        run: wget https://download.virtualbox.org/virtualbox/${{ env.VIRTUALBOX_VERSION }}/Oracle_VM_VirtualBox_Extension_Pack-${{ env.VIRTUALBOX_VERSION }}.vbox-extpack

      - name: "Virtualbox - Install Extension Pack"
        run: sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-${{ env.VIRTUALBOX_VERSION }}.vbox-extpack --accept-license=${{ env.VIRTUALBOX_EXT_PACK_LICID }}

      - name: "Virtualbox - download Guest aditions"
        run: sudo wget -P /opt/VirtualBox https://download.virtualbox.org/virtualbox/${{ env.VIRTUALBOX_VERSION }}/VBoxGuestAdditions_${{ env.VIRTUALBOX_VERSION }}.iso
      #Packer 
      - name: "Ensure Image dir"
        run: mkdir -p final-image
      
      - name: Run packer init
        working-directory: "./packer"
        run: "packer init ."
      - name: Run packer validate
        working-directory: "./packer"
        run: "packer validate ."

      - name: "Packer build ."
        working-directory: "./packer"
        run: "packer build ."
        env:
          BASE_IMAGE_PATH: ".final-image"
      
          
